FROM maven:3.9.11-eclipse-temurin-17 AS build
ARG MODULE
WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/root/.m2 mvn -T 1C -DskipTests -pl ${MODULE} -am package

FROM eclipse-temurin:17-jre
ARG MODULE
WORKDIR /app
COPY --from=build /app/${MODULE}/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
